manage_module_config.example:
  path: '/manage-module-config/example'
  defaults:
    _title: 'Example'
    _controller: '\Drupal\manage_module_config\Controller\ManageModuleConfigController::build'
  requirements:
    _permission: 'access content'

manage_module_config.settings_form:
  path: '/admin/config/system/manage-module-config'
  defaults:
    _title: 'manage module config settings'
    _form: 'Drupal\manage_module_config\Form\SettingsForm'
  requirements:
    _permission: 'administer manage_module_config configuration'
    
    
manage_module_config.manage_entities:
  path: '/admin/config/manage-module-config/{plugin_id}'
  defaults:
    _title: 'Gestion des contenus'
    _controller: '\Drupal\manage_module_config\Controller\ManageModuleConfigController::ManageEntities'
  requirements:
    _role: 'gerant_de_site_web+administrator'
    
manage_module_config.add_config:
  path: '/admin/config/manage-add-plugins/{domain_id}/{site_type_datas_id}'
  defaults:
    _title: 'Add plugin'
    _controller: '\Drupal\manage_module_config\Controller\ManageModuleConfigController::AddPlugin'
  requirements:
    _role: 'gerant_de_site_web+administrator'
