<?php

/**
 *
 * @file
 * Primary module hooks for manage module config module.
 */

/**
 * implement
 */
function manage_module_config_theme($existing, $type, $theme, $path) {
  return [
    'manage_module_config_card_info' => [
      'variables' => [
        'name' => NULL,
        'description' => NULL,
        'route' => NULL,
        'icon_svg' => NULL,
        'icon_svg_class' => NULL,
        'number' => NULL
      ]
    ],
    'manage_module_config_card' => [
      'variables' => [
        'header' => NULL,
        'icon' => NULL,
        'content' => NULL
      ]
    ]
  ];
}