# Schema for the configuration files of the manage module config module.
manage_module_config.settings:
  type: config_object
  label: 'manage module config settings'
  mapping:
    example:
      type: string
      label: 'Example'
